project_id: "glowing-baton-440204-i1"
region: "us-central1"
bqsource: "patient_data"
feature_store_name: "featurestore_bigtable"
feature_groups:
  - name: "name_group"
    features:
      - name: "fname"
        value_type: "STRING"
      - name: "lname"
        value_type: "STRING"
  - name: "medical_history_group"
    features:
      - name: "blood_type"
        value_type: "STRING"
      - name: "diagnosis"
        value_type: "STRING"